---
title: "R Markdown + Shiny"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE, message = FALSE)
```

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(southafricastats)

totals <- population_zaf %>%
        filter(year == 2013) %>%
        select(province, total)

compare_provinces <- mortality_zaf %>%
  left_join(totals) %>%
  mutate(rate = deaths / total * 1e3) %>%
  group_by(province, indicator) %>%
  summarise(rate = mean(rate)) %>%
  ungroup %>%
  left_join(totals) %>%
  spread(indicator,rate)

```

```{r}
ggplot(compare_provinces,
       aes(`Tuberculosis (A15-A19)`,
       `Human immunodeficiency virus [HIV] disease (B20-B24)`,
       label = province)) +
geom_point(aes(size = total), alpha = 0.8, color = "midnightblue") +
  geom_text(vjust = 2.5) +
theme_minimal()
```

```{r}
fillCol(height = 800,
  renderPlot({
      ggplot(selected_df(),
       aes(x,y,
       label = province)) +
geom_point(aes(size = total), alpha = 0.8, color = "midnightblue") +
  geom_text(vjust = 2.5) +
theme_minimal() +
    labs(x = input$x_axis,y = input$y_axis)
        
},height = 800)
)
```

```{r}
selectInput(inputId  = "x_axis",
            label = "select x axis",
            choices = colnames(compare_provinces)[3:20],
            selected = "Tuberculosis (A15-A19)")

selectInput(inputId  = "y_axis",
            label = "select y axis",
            choices = colnames(compare_provinces)[3:20],
            selected = "Human immunodeficiency virus [HIV] disease (B20-B24)")

```

```{r}
selected_df <- reactive({
        subset_df <- compare_provinces[, c(1,2, 
                              which(colnames(compare_provinces)== input$x_axis),
                              which(colnames(compare_provinces) == input$y_axis))]
        colnames(subset_df) <- c("province","total","x","y")
        subset_df
})

```




Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
